{% set name = "ForceBalance" %}
{% set version = "openmm-safe-conditional-imports" %}
{% set sha256 = "30d750f9ffbc0b99b013855a9609bbaec04e1f516aded113c3a2d9dc93e0d0a7" %}

package:
  name: {{ name|lower }}
  version: 1.9.1 

source:
  url: https://github.com/leeping/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - scipy
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - pymbar
    - future
    - networkx
    - lxml
  run_constrained:
    - openforcefield ==9999999999

test:
  imports:
    - forcebalance

about:
  home: http://github.com/leeping/forcebalance/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated force field optimization.

  doc_url: https://leeping.github.io/forcebalance/doc/html/
  dev_url: http://github.com/leeping/forcebalance/

extra:
  recipe-maintainers:
    - leeping
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
