{% set name = "ForceBalance" %}
{% set version = "1.9.3" %}
{% set sha256 = "bbb3ac0591e4f7633aa8974492fada8e542fec39c155b5a56a41322f1a85d22f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leeping/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - scipy
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - pymbar
    - future
    - networkx
    - lxml
  run_constrained:
    - openforcefield ==9999999999

test:
  requires:
    - setuptools
    - openff-toolkit >=0.10.3|<=0.10.0
  imports:
    - forcebalance
    - openff.toolkit

about:
  home: http://github.com/leeping/forcebalance/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated force field optimization.

  doc_url: https://leeping.github.io/forcebalance/doc/html/
  dev_url: http://github.com/leeping/forcebalance/

extra:
  recipe-maintainers:
    - leeping
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
