{% set name = "ForceBalance" %}
{% set version = "1.8.0" %}
{% set sha256 = "5ec434a86932aeb6213513ac5a4fc98952396ce77fa94731471bcd80fdb073c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leeping/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - scipy
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - pymbar
    - future
    - networkx
    - lxml
  run_constrained:
    - openforcefield ==9999999999

test:
  requires:
    - openff-toolkit-base
  imports:
    - forcebalance
    - openff.toolkit

about:
  home: http://github.com/leeping/forcebalance/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated force field optimization.

  doc_url: https://leeping.github.io/forcebalance/doc/html/
  dev_url: http://github.com/leeping/forcebalance/

extra:
  recipe-maintainers:
    - leeping
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
