{% set name = "ForceBalance" %}
{% set version = "1.9.2" %}
{% set sha256 = "fddf45bc2b489af6909b91e599796eb7659444ae9706fade0f88cd001b8646be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leeping/{{ name }}/archive/master.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - scipy
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - pymbar
    - future
    - networkx
    - lxml
  run_constrained:
    - openforcefield ==9999999999

test:
  imports:
    - forcebalance

about:
  home: http://github.com/leeping/forcebalance/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated force field optimization.

  doc_url: https://leeping.github.io/forcebalance/doc/html/
  dev_url: http://github.com/leeping/forcebalance/

extra:
  recipe-maintainers:
    - leeping
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
