{% set name = "ForceBalance" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leeping/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b2988ca6fb103e69eb5a02c8ec55ad9c66bec4d000737b1e6a314d1b88b0064a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - scipy
    - python
    - pip
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - pymbar <4
    - future
    - networkx
    - lxml
  run_constrained:
    - openforcefield ==9999999999
    - openff-toolkit-base >=0.11

test:
  requires:
    - setuptools
  imports:
    - forcebalance

about:
  home: http://github.com/leeping/forcebalance/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automated force field optimization.

  doc_url: https://leeping.github.io/forcebalance/doc/html/
  dev_url: http://github.com/leeping/forcebalance/

extra:
  recipe-maintainers:
    - leeping
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
